"""added overalls

Revision ID: e1ff2120acec
Revises: 8b12b89bb66e
Create Date: 2026-08-03 10:14:48.654055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1ff2120acec'
down_revision: Union[str, Sequence[str], None] = '8b12b89bb66e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection_requests', sa.Column('overall_ai_audio_score', sa.Float(), nullable=True))
    op.add_column('detection_requests', sa.Column('overall_ai_video_score', sa.Float(), nullable=True))
    op.add_column('detection_requests', sa.Column('overall_lipsync_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detection_requests', 'overall_lipsync_score')
    op.drop_column('detection_requests', 'overall_ai_video_score')
    op.drop_column('detection_requests', 'overall_ai_audio_score')
    # ### end Alembic commands ###
